services:
  frontend-dev:
    container_name: frontend-dev
    build: ./frontend-dev/.
    image: frontend-dev:latest
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    working_dir: /app
    command: sh -c 'npm install && npm run host'
    networks:
      - ft_transcendence

  nginx:
    container_name: nginx
    build:
      context: ../
      dockerfile: ./docker/nginx/Dockerfile
    image: nginx-web-server:latest
    volumes:
      - ../frontend/dist:/usr/share/nginx/html
    ports:
      - 80:80
    networks:
      - ft_transcendence

  backend:
    container_name: backend
    build:
      context: ../
      dockerfile: ./docker/backend/Dockerfile
    image: backend:latest
    volumes:
      - ../backend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - ft_transcendence
    env_file:
      - ../.env

networks:
  ft_transcendence:
    name: ft_transcendence
    driver: bridge
