services:
  frontend-dev:
    container_name: frontend-dev
    build: ./frontend-dev/.
    image: frontend-dev:latest
    volumes:
      - ../frontend:/app:delegated
      - frontend_node_deps:/app/node_modules
    networks:
      - ft_transcendence

  backend:
    container_name: backend
    build: ./backend/.
    image: backend:latest
    volumes:
      - ../backend:/app:delegated
      - backend_node_deps:/app/node_modules
    networks:
      - ft_transcendence
    env_file:
      - ../.env

  caddy:
    container_name: caddy
    build: ./caddy/.
    image: caddy-web-server:latest
    volumes:
      - ../frontend/dist:/srv
    ports:  # you can access the frontend on https://localhost:4443
      - "4443:443"  # lets use 4443 as it doesn't need root privileges
      # const NGINX_SERVER in frontend src needs to be set too if port is changed
    networks:
      - ft_transcendence
    depends_on:
      - backend
      - frontend-dev

networks:
  ft_transcendence:
    name: ft_transcendence
    driver: bridge

volumes:
  frontend_node_deps:
    name: frontend_node_deps
    driver: local
  backend_node_deps:
    name: backend_node_deps
    driver: local