services:
  frontend-dev:
    container_name: frontend-dev
    build: ./frontend-dev/.
    image: node:22.14.0
    volumes:
      - ../frontend:/app
    ports:
      - 5173:5173
    working_dir: /app
    command: sh -c 'npm install && npm run host'
  nginx:
    container_name: nginx
    build:
      context: ../
      dockerfile: ./docker/nginx/Dockerfile
    image: nginx:1.27.4
    volumes:
      - ../frontend/dist:/usr/share/nginx/html
    ports:
      - 80:80
  backend:
    container_name: backend
    build:
      context: ../
      dockerfile: ./docker/backend/Dockerfile
    image: backend
    volumes:
      - ../backend:/app
