services:
  frontend-dev:
    container_name: frontend-dev
    image: node:22.14.0
    volumes:
      - ../frontend:/app
    ports:
      - 5173:5173
    working_dir: /app
    command: sh -c 'npm install && npm run host'
