services:
  frontend-dev:
    container_name: frontend-dev
    build: ./frontend-dev/.
    image: frontend-dev:latest
    volumes:
      - ../frontend:/app
      - node_deps:/app/node_modules
    ports:
      - 5173:5173
    networks:
      - ft_transcendence

  nginx:
    container_name: nginx
    build:
      context: ../
      dockerfile: ./docker/nginx/Dockerfile
    image: nginx-web-server:latest
    volumes:
      - ../frontend/dist:/usr/share/nginx/html
    ports:
      - 443:443
      - 80:80
    networks:
      - ft_transcendence
    secrets:
      - source: nginx_ssl_certificate
      - source: nginx_ssl_certificate_key

  backend:
    container_name: backend
    build:
      context: ../
      dockerfile: ./docker/backend/Dockerfile
    image: backend:latest
    volumes:
      - ../backend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - ft_transcendence
    env_file:
      - ../.env
    secrets:
      - source: backend_ssl_certificate
      - source: backend_ssl_certificate_key

networks:
  ft_transcendence:
    name: ft_transcendence
    driver: bridge

volumes:
  node_deps:
    name: node_deps
    driver: local

secrets:
  nginx_ssl_certificate:
    file: ../secrets/nginx_ssl_certificate/ssl_certificate.crt
  nginx_ssl_certificate_key:
    file: ../secrets/nginx_ssl_certificate/ssl_certificate.key
  backend_ssl_certificate:
    file: ../secrets/backend_ssl_certificate/ssl_certificate.crt
  backend_ssl_certificate_key:
    file: ../secrets/backend_ssl_certificate/ssl_certificate.key
