import "./server";
import "./api/sign-up/sign-up";
import "./api/sign-in/sign-in";
import "./api/sign-out/sign-out";
import "./api/oauth/oauth";
import "./api/2fa/activate-2fa";
import "./api/2fa/confirm-2fa";
import "./api/protect-routes/validate-access-token";
import "./api/protect-routes/generate-new-access-token";
